baseURL: "https://geekhouse.top/"
title: "GeekHouse"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-184187677-2

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - html
    - rss
    - json

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: YYJ
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "Home"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Timeline
  #       url: timeline
  #     - name: Tags
  #       url: tags
  #     - name: Archives
  #       url: archives

  # home-info mode
  homeInfoParams:
    Title: "\U0001F44F \U0001F44F \U0001F44F"
    Content: "Geek / Sports Fan / Gamer"

  socialIcons:
    - name: github
      url: https://github.com/yyj08070631
    - name: twitter
      url: https://twitter.com/YYJ86332398
    - name: juejin
      url: https://juejin.cn/user/1116759543253064
    - name: email
      url: mailto:yyj08070631@gmail.com

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/yyj08070631.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: timeline
      name: Timeline
      url: /timeline/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: true
      xhtml: true
#   highlight:
#     # anchorLineNos: true
#     codeFences: true
#     guessSyntax: true
#     lineNos: true
#     style: monokai
