baseURL: "https://geekhouse.top/"
title: "GeekHouse | 不肥的肥羊"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-184187677-2

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - html
    - rss
    - json

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # title: ExampleSite
  description: "FED / Sports Fan / Emmm... / Studying WebGL"
  # keywords: [Blog, Portfolio, PaperMod]
  author: YYJ
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  enableemoji: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "\U0001F44F GeekHouse"
    # icon: /logo.png
    iconHeight: 30

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Timeline
  #       url: timeline
  #     - name: Tags
  #       url: tags
  #     - name: Archives
  #       url: archives

  # home-info mode
  homeInfoParams:
    Title: "\U0001F44F \U0001F44F \U0001F44F"
    Content: "FED / Sports Fan / <a href='/emmm'>Emmm...</a> / Studying WebGL"

  socialIcons:
    - name: github
      url: https://github.com/yyj08070631
    - name: twitter
      url: https://twitter.com/YYJ86332398
    - name: juejin
      url: https://juejin.cn/user/1116759543253064
    - name: email
      url: mailto:yyj08070631@gmail.com
    - name: rss
      url: /index.xml

  analytics:
    google:
      SiteVerificationTag: "1QAB7GLKqHCDECvfwM-cD5bZpswitnFWJxBpemz02Ok"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/yyj08070631/yyj08070631.github.io/edit/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    
  # Gitalk
  Gitalk:
    clientID: "9e2cdfca1be7d4afa5fd" # Your client ID
    clientSecret: "92f0c9b3c70a6fa21595951a9f18a6e74d4f5102" # Your client secret
    repo: "gt1" # The repo to store comments
    owner: "yyj08070631" # Your GitHub ID
    admin: "yyj08070631" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id: "location.pathname" # The unique id of the page.
    labels: "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    body: "location.href" # GitHub issue body.
    perPage: 100 # Pagination size, with maximum 100.
    pagerDirection: "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually: true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode: true # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy: "https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token"
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: timeline
      name: Timeline
      url: /timeline/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: true
      xhtml: true
#   highlight:
#     # anchorLineNos: true
#     codeFences: true
#     guessSyntax: true
#     lineNos: true
#     style: monokai
  staticDir:
    - static
